# -*- coding: utf-8 -*-
"""ImageProcess_Lab1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gBNT_DW4HtLNS4OAqiStRd9yOZLesrJY

**Step One**: upload an Image for processing
"""

from google.colab import files
uploaded = files.upload()

"""**Step Two**: Extract filename"""

filename = 'NO SELECTION YET'
for fn in uploaded.keys():
        filename = fn
print(filename)

"""Step Three: Open *filename* and display it"""

from matplotlib import pyplot as plt
import cv2
if filename != 'NO SELECTION YET':
     img = cv2.imread(filename)
     img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
      #display with pyplot
     plt.imshow(img, aspect='auto')
     plt.title(filename)
     plt.show()
     Vdim = img.shape[0]
     Hdim = img.shape[1]
     Depth = img.shape[2]
     print('Hdim: ' + str(Hdim) + '; Vdim: ' + str(Vdim) + '; Depth: ' + str(Depth))
     print('Pixel at row 20, column 10 value [R G B]: ' + str(img[20][10]))
     print('Pixel data type: '+str(img.dtype))
     print('Image size (bytes): Hdim x Vdim x Depth = '+str(img.size))

"""Convert to HSV and display each component"""

if filename != 'NO SELECTION YET':
     hsv = cv2.cvtColor(img, cv2.COLOR_RGB2HSV)
     img_HSV=cv2.split(hsv);
           #display with pyplot
     fig = plt.figure(figsize=(12, 6), dpi=80)
     ax = fig.add_subplot(131, aspect='auto')
     ax.imshow(img_HSV[0], cmap='gray', vmin=0, vmax=180)
     ax.set_title('Hue')
     ax = fig.add_subplot(132, aspect='auto')
     ax.imshow(img_HSV[1], cmap='gray', vmin=0, vmax=255)
     ax.set_title('Sat')
     ax = fig.add_subplot(133, aspect='auto')
     ax.imshow(img_HSV[2], cmap='gray', vmin=0, vmax=255)
     ax.set_title('Value')