# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/salexa211/Desktop/Decimal_Counter/Decimal_Counter.cache/wt [current_project]
set_property parent.project_path C:/Users/salexa211/Desktop/Decimal_Counter/Decimal_Counter.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/salexa211/Desktop/Decimal_Counter/Decimal_Counter.srcs/sources_1/new/Multiplexer_4way.v
  C:/Users/salexa211/Desktop/Decimal_Counter/Decimal_Counter.srcs/sources_1/new/Generic_Counter.v
  C:/Users/salexa211/Desktop/Decimal_Counter/Decimal_Counter.srcs/sources_1/imports/Downloads/seven_seg.v
  C:/Users/salexa211/Desktop/Decimal_Counter/Decimal_Counter.srcs/sources_1/new/Counter_wrapper.v
}
read_xdc C:/Users/salexa211/Desktop/Decimal_Counter/Decimal_Counter.srcs/constrs_1/imports/Downloads/MasterXDC_Nexys4.xdc
set_property used_in_implementation false [get_files C:/Users/salexa211/Desktop/Decimal_Counter/Decimal_Counter.srcs/constrs_1/imports/Downloads/MasterXDC_Nexys4.xdc]

synth_design -top Counter_wrapper -part xc7a100tcsg324-1
write_checkpoint -noxdef Counter_wrapper.dcp
catch { report_utilization -file Counter_wrapper_utilization_synth.rpt -pb Counter_wrapper_utilization_synth.pb }
