# -*- coding: utf-8 -*-
"""Audio-to-spectrogram.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c9GA5r9ljgv8hPhh0vJRfTZlWxkiTwEH

Load a chosen audio file from the user
"""

from google.colab import files
uploaded = files.upload()

"""Extract the filename of the selected file"""

filename = 'No Selection Yet'
for fn in uploaded.keys():
          filename = fn
print(filename)

"""Import the libary functions along with extracting the the signal (x) and sampling rate from the waveform (sr)"""

import matplotlib.pyplot as plt
import librosa
import librosa.display

#use Librosa.load to load the chosen audio file into an array
x, sr = librosa.load(filename)

"""the following will display the chosen waveform in a spectrogram"""

X = librosa.stft(x)
Xdb = librosa.amplitude_to_db(abs(X))
plt.figure(figsize=(14, 5))
librosa.display.specshow(Xdb, sr=sr, x_axis='time', y_axis='hz')
plt.colorbar()
plt.title('Spectrogram of ' + filename)
plt.show()